### ISSUE TITLE
System hangs every once in a while while downloading files

### ISSUE THREAD

**Issue by dudefoxlive** [anatol/pacoloco#6] opened 2020-02-22 03:49 UTC
After finally getting this all working I have noticed that when it is downloading a large number of new files it seems to cause the VM to hand for about close to 10 seconds. Some downloads fail cause if it and others will pick up shortly after. I noticed the issue when I was ssh into the server and when it froze downloading files ssh also froze. Any ideas would be nice.

The VM is a Hyper-V VM with 1 GB of ram and 1 core. If I should increase those I will.

Many thanks.

**Comment by anatol** [comment] 2020-02-26 02:08
> VM to hand for about close to 10 seconds

How exactly it hangs? Do you see CPU usage spike or something else?

> Some downloads fail cause if it and others will pick up shortly after.

It sounds like a duplicate of #5

**Comment by dudefoxlive** [comment] 2020-02-28 04:07
So update. 
Q. How exactly it hangs? Do you see CPU usage spike or something else?
A. After some troubleshooting, I have determined that it's not freezing but the system seems to become unresponsive at times. IE when I've connected over SSH to the machine the SSH freezes when it says updating the package repositories. (This might be due to the Hyper-V VM that I'm using). I don't notice the CPU spiking like crazy. seems to stay within 10% at almost all times.

I'm noticing that while it is downloading the package repositories on the server sometimes it is taking longer than 10 seconds and then the client bails out. I am also noticing while watching journalctl on the service that it is attempting to download the sig for the repositories and failing with error code 404. (Picture has been provided) Not sure if this is also contributing to the small lockups. 

![27-02-2020_22-56-22](https://user-images.githubusercontent.com/50186495/75509420-83002980-59b5-11ea-9f74-90da56ca510d.png)

**Comment by anatol** [comment] 2020-02-28 06:57
> I've connected over SSH to the machine the SSH freezes when it says updating the package repositories. I don't notice the CPU spiking like crazy. seems to stay within 10% at almost all times.

What you see might be because the network to your VM is saturated. SSH is unable to send any packages and thus it looks unresponsive.

> is taking longer than 10 seconds and then the client bails out

This is a known issue. See #5. There is a possible fix in branch https://github.com/anatol/pacoloco/tree/concurrent-download Could you please download it and see if it fixes your "client bailout" issue?

>  the sig for the repositories and failing with error code 404

This error is ok. This is because arch repositories are marked as `SigLevel = Optional`and `pacman` tries to pull them, but the repos are not signed actually.

**Comment by dudefoxlive** [comment] 2020-02-29 16:42
after downloading the concurrent-download it seems to be working great. Gonna test it some more and make sure its working stable.

**Closed** 2020-03-02 20:50 UTC
