### ISSUE TITLE
Docker container TLS handshake timeout

### ISSUE THREAD

**Issue by Rushmore75** [anatol/pacoloco#96] opened 2023-10-24 22:22 UTC
I was only able to get the docker container to complete the TLS handshake when using `network_mode: "host"`. Is this normal? This isn't really an issue for me to run it as such, but it isn't documented in the readme at all

**Comment by anatol** [comment] 2023-10-24 22:48
Cc @dezeroku @HarHarLinks @ilya-zlobintsev

**Comment by dezeroku** [comment] 2023-10-25 03:09
I believe this is a duplicate of https://github.com/anatol/pacoloco/issues/95?

Anyway, this is about the local docker build, right? If so it's the infamous "works on my machine" I'm afraid, I was able to build current master without issues just now.

IMHO it looks like a firewall issue of some kind, especially if the host networking works fine. Could you say a bit more about the environment that you try to build in?

**Comment by Rushmore75** [comment] 2023-10-25 16:00
I'm now using the pre-built version since it wasn't compiling as mentioned in #95 

Not particularly sure what you'd like to know about the environment. It's an Artix Linux headless device that *should* have it's networking in a pretty default mode.

**Comment by HarHarLinks** [comment] 2023-10-27 21:36
not sure why i'm being pinged. i use the exact docker-compose from the readme and it works.

**Closed** 2023-10-27 21:57 UTC
